language: node_js

node_js:
   - node

before_script: 
   - npm install -g --silent @angular/cli

script: 
   - npm test

notifications:
  email: # only receive email when the build status changes (someone broke the build!) 
    on_failure: change
    on_success: change   