language: node_js

node_js:
  - "10"

sudo: false

before_script: 
   - npm install -g --silent @angular/cli
   - ls

script: 
   - npm run test-ci
   - npm run build-ci

notifications:
  email: # only receive email when the build status changes (someone broke the build!) 
    on_failure: change
    on_success: change
  slack:
    on_success: always
    secure: SXXbjDxEIBmsj/MEc32cSN+ZqK7pVKsubxr2dxCC/ifYE+lkDvUcy4X6b02fk5Bm3WlA7x/QMfpA5FNVLcxseUtA9NoquW8CklGDGj4gIVKFbIywIWuEGzKIHujgaFOl6K3Shysmq6zdnsPLIOfUqQzZnb7PmX1ueDKk5kXVBrHQ3usXQ/AMzDDASzBkz0o9ldUkYMqFTjGCJPTjoJp5d8eaduWRAPGR31Tf70JjrE+kHxPL/MLeDXMpGJWuUL0PDOXWauUKSsrLum78hzMwgGVEsGWzmr9j3VJpPLK2HKA4CrOdFKTfNR+m80OHLhDD/WhtjC7+I2vQLg9dP7TMgbmUl2y/sPwvglMRwFQeA5QRcV6t82VH40vxyqMshYSfuXPJ5MzAzh4EuRZPXjLbRuZ2x69PEgcsnsqkbBHSTlvBHfftopiek2i37jd4kPZ3sp1pczjg0nN4fFbkYOYn9QEjyTLHr0TmvyCef3x3Oo6/yCvVKVUe3fPwYzIfINM51zzk7NAnRwXTA6Nz8W1akRi3+7z2Is58Q6fB83q8FRxjZVkCRRJWbDTYNoO4mymtv1Oui79agD6WAmuCf0v0VPUYRPlcc7R78smQr+ENIdEWGDuvlYEG9/KAdgqVanFeLmyjjeI5zvOtqbuHdOYN1y8WjrySPwVS5CkHHHWoH4Y=
