language: node_js

node_js:
  - "10"

sudo: false

before_script: 
   - npm install -g --silent @angular/cli

script: 
   - npm run build-ci

notifications:
  email: # only receive email when the build status changes (someone broke the build!) 
    on_failure: change
    on_success: change   