language: node_js
node_js:
- '10'
sudo: false
before_script:
- npm install -g --silent @angular/cli
- ls
script:
- npm run test-ci
- npm run build-ci
notifications:
  email:
    on_failure: change
    on_success: change
  slack:
    on_success: always
    rooms:
      secure: Nc8nY1hxFJ3YlX/CqFNUYfyTMSkGosg1qg7ekCZHXH21lw/H/b32x0cK+3AWZqWejg3OLd/h5Ux74+oajlLe3xgyydqBrk543P3xt8/4MIIXxw/fnDI8TjhJNxa9Jl3OfyycIPNwzUzw8yMiXv/2C0BKnwBRqJwsORxvNqZrDOLnvlftSZhwGcpoJIdgWxq9aqQ8DTuCA/lMha237vvXuTe4crUWFFk2/9kZ3SYkkfPkhYltfV5LVdrv96PtrNovTKdhfdt/qe/d/dLb3ECsQLxqzNsgtzCL7+uSy73wQPoS1z0P3uJYptHTzwFM+zxAuDUEk3DNDnn+i2fiKypmHOI8Lhi3dC1Ef4ip0u2I8Ke9n9ikfjJsH2EGEVqNLypqE/IaFjz8Caks7nDNF30fQGU44r6zebLf+IEPqpHCes7FXDIP6DDnK0Ma3ysV7ybmw6FY5m1wZVxJgCavpNlEUfSuYogTq7NyNzp2im2JT0w6pRLlJHr67cS1VrgjWdTEaEa93ZjkIRHqb0cjbenH6IUEmJYZ5Lps5k70JVR2yBVNjwjmPJ6uTIOzZKTfsUAEDUoLPwbg+wAerZykMDwyMkSO3H78eh2vl3zAR3S6MTUKB3Bohr6I5pE8wYhoRQnIDR0nk7GUFd4RCJ9uuKr29dBuIXZ+OpXZd4b0kDOshfc=
